# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-18 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_content1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='content1',
        ),
    ]
