# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-18 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_delete_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('use_id', models.CharField(max_length=10)),
                ('use_name', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=2000)),
            ],
        ),
    ]
