# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-18 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='use_id',
        ),
        migrations.RemoveField(
            model_name='content',
            name='use_name',
        ),
    ]
